/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jungfrau_3d/etherlaken-Main_Building_Tower.gltf --transform -t -o src/interlaken/Main_Building_Tower.tsx 
Files: jungfrau_3d/etherlaken-Main_Building_Tower.gltf [1.83KB] > /Users/klemenkunstek/Desktop/Akasha/map-threejs/render-app/src/interlaken/etherlaken-Main_Building_Tower-transformed.glb [1.78KB] (3%)
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGLTF,  } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Main_Building_Tower: THREE.Mesh
  }
  materials: {
    mat_0: THREE.MeshStandardMaterial
  }
  animations: GLTF['animations']
}

export function Main_Building_Tower(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/etherlaken-Main_Building_Tower-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Main_Building_Tower.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/etherlaken-Main_Building_Tower-transformed.glb')
