/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 etherlaken-Outer_Ring_Inner_Passages.gltf --transform -t -o ../src/interlaken/Outer_Ring_Inner_Passages.tsx 
Files: etherlaken-Outer_Ring_Inner_Passages.gltf [10.84KB] > /Users/klemenkunstek/Desktop/Akasha/map-threejs/render-app/src/interlaken/etherlaken-Outer_Ring_Inner_Passages-transformed.glb [1.58KB] (85%)
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF,  } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ring_Passages: THREE.Mesh
  }
  materials: {
    mat_0: THREE.MeshStandardMaterial
  }
  animations: GLTF['animations']
}

export function Outer_Ring_Inner_Passages(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/etherlaken-Outer_Ring_Inner_Passages-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ring_Passages.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/etherlaken-Outer_Ring_Inner_Passages-transformed.glb')
