/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 etherlaken-Outer_Ring.gltf --transform -t -o ../src/interlaken/Outer_Ring.tsx 
Files: etherlaken-Outer_Ring.gltf [2.75KB] > /Users/klemenkunstek/Desktop/Akasha/map-threejs/render-app/src/interlaken/etherlaken-Outer_Ring-transformed.glb [2.87KB] (-4%)
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGLTF,  } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ring_Structure: THREE.Mesh
  }
  materials: {
    mat_0: THREE.MeshStandardMaterial
  }
  animations: GLTF['animations']
}

export function Outer_Ring(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/etherlaken-Outer_Ring-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ring_Structure.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/etherlaken-Outer_Ring-transformed.glb')
