/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jungfrau_3d/etherlaken-Main_Building_F0.gltf --trasform 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/etherlaken-Main_Building_F0.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Main_Building_F0_1.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_2.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_3.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_4.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_5.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_6.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_7.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_8.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_9.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_10.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_11.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_12.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_13.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_14.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_15.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_16.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_17.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_18.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_19.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_20.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_21.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Main_Building_F0_22.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/etherlaken-Main_Building_F0.gltf')
