/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./scene.gltf --transform 
Files: ./scene.gltf [7.16KB] > /Users/klemenkunstek/Desktop/Akasha/map-threejs/boring_commercialoffice_two-story_building/scene-transformed.glb [789.53KB] (-10927%)
Author: Full_Metal_Dipshit (https://sketchfab.com/Potato_Pizza)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/boring-commercialoffice-two-story-building-aa7ff84baa8a4b38affaa38acdc0d7b1
Title: Boring Commercial/Office two-story Building
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props: { toggle: boolean }) {
  const { toggle } = props;
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Office_Windows_Ventilation_0.geometry}
        material={materials.Windows_Ventilation}
        scale={0.01}
      />
      {toggle && (
        <mesh
          geometry={nodes.Office_Main_Body_0.geometry}
          material={materials.Main_Body}
          scale={0.01}
        />
      )}
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
